/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package review;

public class App {
    public static void main(String[] args) {
        String grades = "amber,,green";
        Report report = new Report(grades);
        System.out.println(report.getFormattedReport());
    }
}
